[package]
name = "blinky-demo"
version = "0.1.0"
authors = ["Robert Wiewel <dev@ducktec.de>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/ducktec/esp32c3-hal"
description = "Demo: Blink an external LED"
license = "MIT OR Apache-2.0"

[dependencies]
esp32c3-hal = { path = "../esp32c3-hal" }
riscv = "0.6.0"
nb = "0.1.2"
void = { version = "1.0", default-features = false }
esp32c-rt = "0.1.1"
panic-halt = "0.2"
